ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.mezhendosina.RoutingKt.configureSerialization
      - com.mezhendosina.RoutingKt.configureCORS
      - com.mezhendosina.RoutingKt.configureStatusPages
      - com.mezhendosina.RoutingKt.configureSecurity
      - com.mezhendosina.RoutingKt.configureRouting
